apiVersion: v1
kind: Secret
metadata:
  name: opensearch-credentials
  namespace: obser
type: Opaque
stringData:
  username: "admin"                 # same as terraform master_user_name
  password: "khanKHanb@101"   # same as terraform master_user_password
  endpoint: "https://search-k8s-logs-demo-7cmz4tzx6kouoiaoajmpzmgpnq.us-east-1.es.amazonaws.com"
