apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: obser
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    filter {
      if [kubernetes] {
        mutate {
          add_field => {
            "kubernetes_namespace" => "%{[kubernetes][namespace_name]}"
            "kubernetes_pod"       => "%{[kubernetes][pod_name]}"
            "kubernetes_node"      => "%{[kubernetes][host]}"
          }
        }
      }
    }

    output {
      opensearch {
        hosts    => [ "https://${OPENSEARCH_ENDPOINT}:443" ]
        user     => "${OPENSEARCH_USER}"
        password => "${OPENSEARCH_PASSWORD}"

        index    => "k8s-logs-%{+YYYY.MM.dd}"

        ssl                      => true
        ssl_certificate_verification => false
      }
    }
